In [1]:
import tensorflow as tf

In [3]:
tf.__version__

'2.20.0'

In [4]:
import numpy as np

In [5]:
!pip show tensorflow

Name: tensorflow
Version: 2.20.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\users\saipr\anaconda3\envs\tensorflow_env\lib\site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google_pasta, grpcio, h5py, keras, libclang, ml_dtypes, numpy, opt_einsum, packaging, protobuf, requests, setuptools, six, tensorboard, termcolor, typing_extensions, wrapt
Required-by:

In [6]:
!pip show keras

Name: keras
Version: 3.12.3
Summary: Multi-backend Keras
Home-page:
Author:
Author-email: Keras team <keras-users@googlegroups.com>
License: Apache License 2.0
Location: c:\users\saipr\anaconda3\envs\tensorflow_env\lib\site-packages
Requires: absl-py, h5py, ml-dtypes, namex, numpy, optree, packaging, rich
Required-by: tensorflow

In [8]:
import numpy as np
print("numpy:", np.__version__)

numpy: 2.2.6

In [9]:
import keras
print("keras:", keras.__version__)

keras: 3.12.3

In [10]:
import google.protobuf
print("protobuf:", google.protobuf.__version__)

protobuf: 7.35.1

In [11]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv(r"C:\EXCEL DATA\Energy_Ann.csv")

In [13]:
df

     Temperature  Pressure  Humidity  Vaccum  Energy
0          20.99   1000.63     55.13   36.16  490.48
1          21.92   1022.30     44.78   46.10  477.80
2          10.47   1012.63     41.46   34.94  498.33
3          18.62   1005.51     72.41   65.47  476.10
4          25.15   1017.45     58.71   32.77  491.63
..           ...       ...       ...     ...     ...
295        25.03   1018.18     44.34   55.12  486.52
296        18.64   1008.03     44.40   58.05  482.64
297        20.07   1010.65     77.94   42.58  479.00
298        26.75   1008.81     94.90   38.73  488.84
299        28.70   1001.88     75.06   43.17  483.94

[300 rows x 5 columns]

In [14]:
df.shape

(300, 5)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Temperature  300 non-null    float64
 1   Pressure     300 non-null    float64
 2   Humidity     300 non-null    float64
 3   Vaccum       300 non-null    float64
 4   Energy       300 non-null    float64
dtypes: float64(5)
memory usage: 11.8 KB

In [16]:
df.describe()

       Temperature     Pressure    Humidity      Vaccum      Energy
count   300.000000   300.000000  300.000000  300.000000  300.000000
mean     18.331000  1012.063333   68.745800   49.541567  486.792333
std       7.201293     7.140010   15.272927   14.321026    7.889490
min       5.090000  1000.070000   40.300000   25.080000  469.220000
25%      11.792500  1005.935000   55.507500   37.607500  481.177500
50%      19.090000  1012.010000   69.885000   48.565000  486.660000
75%      24.885000  1018.022500   80.972500   62.347500  492.472500
max      30.000000  1024.940000   94.900000   74.960000  503.400000

In [17]:
df.columns.tolist()

['Temperature', 'Pressure', 'Humidity', 'Vaccum', 'Energy']

In [18]:
# step-1
#project understanding
# predict the wind energy based on atmospheric conditions
#

In [19]:
df['Pressure'].unique()

array([1000.63, 1022.3 , 1012.63, 1005.51, 1017.45, 1002.32, 1018.24,
       1020.74, 1001.15, 1002.53, 1005.24, 1004.28, 1016.  , 1005.73,
       1023.57, 1022.86, 1006.57, 1024.94, 1015.69, 1024.9 , 1018.02,
       1002.79, 1006.58, 1007.46, 1013.48, 1000.49, 1001.45, 1001.73,
       1013.75, 1016.25, 1008.45, 1015.78, 1005.95, 1014.28, 1002.42,
       1016.83, 1021.54, 1006.96, 1013.76, 1023.16, 1010.03, 1019.6 ,
       1013.89, 1014.48, 1012.57, 1004.65, 1022.26, 1014.59, 1005.97,
       1018.8 , 1001.83, 1021.98, 1015.29, 1007.48, 1002.68, 1005.09,
       1021.15, 1019.28, 1010.69, 1013.64, 1007.71, 1005.25, 1010.16,
       1024.41, 1008.3 , 1006.67, 1005.56, 1005.69, 1024.17, 1013.41,
       1024.06, 1007.84, 1006.37, 1017.99, 1016.61, 1007.51, 1003.18,
       1015.39, 1010.75, 1005.34, 1002.12, 1018.78, 1006.12, 1015.74,
       1016.4 , 1010.63, 1006.23, 1024.7 , 1017.98, 1018.59, 1019.15,
       1007.14, 1005.78, 1013.57, 1014.6 , 1000.15, 1010.48, 1005.49,
       1010.11, 1000.67, 1003.39, 1008.17, 1006.31, 1008.75, 1023.74,
       1016.74, 1004.19, 1024.12, 1023.95, 1015.68, 1003.03, 1009.26,
       1002.64, 1010.89, 1013.45, 1021.29, 1011.62, 1004.55, 1017.53,
       1018.  , 1012.27, 1007.66, 1018.65, 1003.02, 1004.63, 1013.12,
       1004.49, 1013.83, 1021.82, 1001.28, 1001.85, 1007.6 , 1019.77,
       1021.5 , 1018.5 , 1003.93, 1014.85, 1011.35, 1016.53, 1022.71,
       1018.72, 1017.49, 1001.  , 1024.05, 1016.81, 1016.29, 1012.29,
       1021.44, 1020.34, 1024.25, 1013.56, 1015.64, 1010.95, 1005.98,
       1024.81, 1012.46, 1024.51, 1012.71, 1010.37, 1013.46, 1008.04,
       1019.39, 1009.65, 1000.93, 1011.01, 1016.37, 1017.32, 1009.5 ,
       1000.9 , 1018.67, 1011.09, 1007.33, 1019.81, 1006.02, 1006.38,
       1003.95, 1010.61, 1012.08, 1007.38, 1017.14, 1022.6 , 1015.92,
       1020.96, 1011.02, 1018.69, 1013.27, 1012.05, 1024.07, 1024.5 ,
       1000.35, 1014.61, 1001.58, 1003.49, 1022.18, 1023.65, 1002.48,
       1004.75, 1016.04, 1003.15, 1005.4 , 1000.07, 1004.36, 1013.15,
       1002.73, 1021.67, 1011.97, 1001.84, 1015.83, 1011.34, 1016.27,
       1005.71, 1010.67, 1001.68, 1020.29, 1003.06, 1018.03, 1005.32,
       1009.19, 1024.36, 1023.23, 1007.72, 1010.02, 1005.38, 1019.42,
       1015.45, 1011.05, 1007.08, 1009.88, 1003.43, 1004.39, 1020.16,
       1023.03, 1010.44, 1006.08, 1008.49, 1012.75, 1020.38, 1019.01,
       1018.86, 1015.88, 1001.71, 1012.68, 1001.92, 1011.57, 1020.25,
       1001.55, 1012.61, 1013.07, 1008.46, 1002.36, 1022.66, 1023.45,
       1016.75, 1016.15, 1005.35, 1001.93, 1022.09, 1009.42, 1004.14,
       1011.1 , 1007.74, 1023.68, 1013.19, 1006.25, 1022.63, 1011.28,
       1005.89, 1020.98, 1000.13, 1018.18, 1001.19, 1003.59, 1015.89,
       1008.62, 1008.31, 1019.48, 1004.99, 1013.58, 1019.52, 1022.24,
       1012.41, 1008.03, 1010.65, 1008.81, 1001.88])

In [20]:
df['Pressure'].nunique()

285

In [21]:
df['Temperature'].unique()

array([20.99, 21.92, 10.47, 18.62, 25.15, 13.41, 25.18, 18.8 , 22.61,
       10.82, 14.25, 20.23, 29.74, 24.4 , 10.27, 14.89, 19.03, 10.48,
        7.74, 14.54,  5.29, 21.02, 26.9 , 26.76, 24.06, 13.1 , 12.69,
       17.15, 16.88, 10.29, 29.88, 10.62,  6.77, 28.39,  9.76, 23.23,
       13.48, 15.55, 26.53, 29.22, 10.34, 11.63, 29.89, 19.6 ,  7.  ,
        8.  , 15.48, 22.9 , 12.9 , 29.9 , 27.02, 22.59, 25.43,  7.89,
       22.94, 27.63,  5.09, 18.79, 27.6 ,  8.19, 27.47, 27.1 , 26.62,
       23.41, 25.27, 26.46, 24.88, 26.61, 29.53,  9.46, 23.21, 19.41,
       18.46,  6.75, 22.99, 12.39, 27.57, 12.17, 16.05,  9.24, 25.46,
        5.61, 15.36, 11.1 ,  7.66,  6.26, 21.69, 20.32, 27.43, 20.94,
        6.94,  8.46, 15.19, 27.62, 14.51, 28.84, 10.51, 21.98, 20.56,
       21.07, 25.8 , 30.  , 23.86,  8.16, 24.17, 25.48, 21.93, 22.27,
       20.01, 15.71, 25.56, 22.68, 25.2 , 11.71, 26.27, 27.01,  7.14,
       21.15, 22.29, 15.64, 11.29, 24.05, 29.42, 10.69, 29.36, 17.27,
        9.61, 15.02, 19.07, 20.16, 16.07, 20.24, 21.51, 16.26, 22.57,
       20.63, 21.19, 22.22,  7.01,  7.28, 29.99, 16.76, 20.87, 21.75,
       28.63, 13.08, 21.44, 23.91, 28.19, 20.22,  7.33, 25.87, 28.05,
       24.75, 12.07,  8.71, 16.38, 10.84, 25.29, 17.38, 26.85, 15.25,
       13.46, 26.48, 26.81, 29.94, 24.9 , 19.15, 20.49, 11.35, 21.94,
       20.97, 14.62, 29.82, 17.42, 13.81, 21.48, 12.72, 12.38, 29.29,
       25.62,  7.88, 23.11, 24.77, 21.81, 10.85, 10.53, 15.21,  7.43,
       23.58, 15.37,  5.82,  7.48, 14.95, 21.57, 11.09, 10.18, 27.51,
       11.27, 23.54, 17.83, 24.58,  6.52, 27.74, 11.88, 18.26, 26.32,
       16.29,  7.38, 28.07, 23.47, 13.24, 26.7 , 19.45, 26.13,  5.66,
       19.16, 23.65, 23.04,  8.94, 17.14, 15.75,  6.14, 10.28, 23.68,
       25.83,  5.47, 22.74, 25.03, 26.11, 12.76,  7.85, 25.47, 20.06,
       17.35, 19.11,  8.77,  6.4 , 25.79, 17.68, 16.24, 22.86, 15.99,
       15.22,  6.65, 21.41,  8.54, 19.88, 25.33, 18.16,  9.51,  8.44,
       25.88,  8.28, 25.23, 10.94, 18.35, 14.2 , 14.55,  7.56, 11.82,
       10.55, 17.55, 28.27, 16.22, 18.72, 12.53,  7.77, 11.05, 15.41,
       18.15, 16.75, 24.71, 23.38,  9.38,  6.1 , 29.73, 13.92, 29.34,
       18.64, 20.07, 26.75, 28.7 ])

In [22]:
df['Temperature'].nunique()

283

In [23]:
x = df.drop(columns = 'Energy')
y = df['Energy']

In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [74]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state=42)

In [75]:
x_train

     Temperature  Pressure  Humidity  Vaccum
232        15.75   1007.08     77.32   49.33
59         18.79   1010.69     40.53   28.76
6          25.18   1018.24     69.49   73.66
185        12.72   1011.02     71.88   61.62
173        24.90   1007.33     60.62   32.28
..           ...       ...       ...     ...
188        25.62   1012.05     84.36   62.33
71          9.46   1024.06     54.60   30.42
106         8.16   1016.74     71.02   35.90
270        14.55   1013.19     93.14   65.84
102        10.29   1008.17     81.87   43.96

[240 rows x 4 columns]

In [27]:
x_test

     Temperature  Pressure  Humidity  Vaccum
203        11.09   1003.15     71.05   28.43
266        25.23   1004.14     64.07   45.54
152        23.91   1015.64     81.80   35.18
9          10.82   1002.53     55.29   56.78
233         6.14   1009.88     72.96   25.38
226        22.57   1007.72     58.69   25.31
196         7.43   1022.18     47.46   47.68
109        21.93   1023.95     61.82   60.75
5          13.41   1002.32     45.32   67.37
175        20.49   1006.02     90.21   32.16
237         5.47   1023.03     87.42   53.79
57         27.63   1021.15     45.08   46.18
218        28.07   1001.68     85.75   29.66
45         19.60   1012.57     86.90   32.87
182        17.42   1022.60     55.74   64.94
221        26.70   1018.03     93.26   55.02
289        25.29   1001.58     82.69   47.88
211         6.52   1011.97     62.09   59.30
148        21.75   1021.44     58.14   59.68
165        17.38   1000.93     67.63   54.51
78         27.57   1015.39     56.55   52.40
113        25.56   1002.64     92.84   56.78
249        25.79   1001.92     87.53   67.76
250        17.68   1011.57     70.49   64.59
104        30.00   1008.75     75.76   64.06
42         11.63   1019.60     65.03   46.15
281         7.77   1022.63     72.82   25.82
295        25.03   1018.18     44.34   55.12
157        25.87   1024.51     53.41   52.56
238        22.74   1010.44     46.33   26.04
17         10.48   1024.94     68.02   29.55
164        25.29   1009.65     76.50   66.04
33          6.77   1005.95     76.79   35.71
24         24.06   1013.48     82.82   51.52
215        26.32   1016.27     82.29   61.04
119        27.01   1017.53     55.19   25.51
7          18.80   1020.74     74.02   68.09
90         27.43   1018.59     66.11   37.96
46          7.00   1004.65     72.73   58.76
73         19.41   1006.37     78.98   25.08
93          8.46   1005.78     78.17   60.32
76         22.99   1007.51     57.01   45.42
286        24.71   1008.62     80.31   56.41
60         27.60   1013.64     85.90   54.13
77         12.39   1003.18     63.12   72.02
63         27.10   1010.16     74.14   32.73
234        10.28   1003.43     54.05   41.41
229        23.04   1019.42     71.22   29.25
111        20.01   1003.03     94.11   64.13
231        17.14   1011.05     55.02   62.75
180        29.82   1007.38     93.79   57.91
144         7.28   1024.05     85.98   53.76
239        25.03   1015.45     85.76   70.99
75          6.75   1016.61     58.16   40.70
297        20.07   1010.65     77.94   42.58
278        16.22   1000.13     44.36   37.80
97         28.84   1010.48     81.11   52.31
92          6.94   1007.14     54.94   40.99
192        21.81   1014.61     85.23   72.01
25         13.10   1000.49     91.10   68.94

In [28]:
y_train

232    491.34
59     496.29
6      476.02
185    482.92
173    484.74
        ...
188    476.25
71     496.45
106    500.36
270    491.84
102    497.81
Name: Energy, Length: 240, dtype: float64

In [29]:
y_test

203    499.78
266    484.65
152    485.22
9      489.63
233    496.94
226    493.12
196    499.35
109    476.04
5      489.99
175    486.54
237    497.67
57     477.13
218    474.98
45     495.40
182    487.60
221    476.69
289    477.67
211    494.85
148    479.74
165    492.51
78     471.42
113    484.52
249    479.35
250    491.44
104    477.57
42     500.38
281    499.38
295    486.52
157    479.22
238    484.48
17     489.33
164    486.31
33     491.99
24     473.78
215    474.07
119    491.16
7      485.13
90     477.55
46     490.03
73     496.13
93     485.82
76     482.32
286    484.77
60     472.86
77     490.96
63     489.11
234    486.71
229    479.18
111    480.14
231    479.93
180    472.19
144    502.33
239    471.49
75     503.40
297    479.00
278    495.83
97     479.43
92     498.06
192    474.22
25     492.68
Name: Energy, dtype: float64

In [76]:
import tensorflow as tf
import keras

In [77]:
from keras.models import Sequential
from keras.layers import Dense

#  First  applying Perceptron model --no neurons or layers only i/p and o/p

In [101]:
#initialization of neural network

p_model = Sequential()  #order of excecution

#add layer
p_model.add(Dense(input_dim=4, units=1, activation='relu', kernel_initializer="uniform"))

#compile - calculate

p_model.compile(optimizer='adam', loss='mean_squared_error') #applying gradient descent algo

C:\Users\saipr\anaconda3\envs\tensorflow_env\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [103]:
#fit the train data

p_model.fit(x_train, y_train, batch_size=32, epochs=50)

Epoch 1/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8438
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 237194.8281
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 237194.8281
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 237194.8125
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 237194.8281
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 237194.8281
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8438
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8438
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 237194.8438
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 237194.8281
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 237194.8281
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 237194.8281
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8281
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 237194.8281
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 237194.8281
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8438
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8438
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8438
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8438
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8281
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 237194.8438
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8438
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8125
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8594
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8281
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8438
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8281
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8281
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 237194.8281
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8438
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8281
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8281
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8438
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8438
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237194.8438
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 237194.8438

In [104]:
#predict on train data
ypred_train = p_model.predict(x_train)

## evaluate the train data
from sklearn.metrics import mean_squared_error
train_mse = mean_squared_error(y_train, ypred_train)
train_rmse = np.sqrt(train_mse)
print("train_RMSE:",train_rmse)

8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
train_RMSE: 487.0265283410306

In [105]:
#Predicy on test data

ypred_test = p_model.predict(x_test)

##evluate on test data

test_mse = mean_squared_error(y_test, ypred_test)
test_rmse = np.sqrt(test_mse)
print("test RMSE:", test_rmse)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
test RMSE: 486.173533382543

**ANN** --> Now we are going to apply ANN model

-Design
--fit
--Predict
--Evaluation

In [106]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state=42)

In [112]:
#Design of Neural Networks

#add layers

p_model.add(Dense(input_dim=4, units=1, activation='relu', kernel_initializer="uniform"))


nn1= Sequential()

nn1.add(Dense(input_dim=4, units=8, activation='relu', kernel_initializer ='uniform'))
nn1.add(Dense(units=8, activation='relu', kernel_initializer='uniform'))
nn1.add(Dense(units=1, activation='linear', kernel_initializer='he_uniform'))

#compile calculate

nn1.compile(optimizer='adam', loss='mean_squared_error')

#fit the data
nn1.fit(x_train, y_train, batch_size=32, epochs=50)

#predict on train data

ypred_train = nn1.predict(x_train)
ypred_test = nn1.predict(x_test)

#evaluate train data
from sklearn.metrics import mean_squared_error
train_mse = mean_squared_error(y_train, ypred_train)
train_rmse = np.sqrt(train_mse)
print("train_rmse:", train_rmse)

#evaluate test data
test_mse = mean_squared_error(y_test, ypred_test)
test_rmse = np.sqrt(test_mse)
print("test rmse :", test_rmse)

Epoch 1/50

C:\Users\saipr\anaconda3\envs\tensorflow_env\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 237282.2812
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 235735.7812
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 234663.9219
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 233261.9219
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 231331.0469
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 228708.7812
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 225275.0156
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 220928.1406
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 215594.2031
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 209223.1719
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 201796.7656
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 193310.4688
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 183801.7344
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 173333.8281
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 162000.6875
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 149909.3125
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137224.3906
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 124119.8750
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 110793.0547
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 97476.8281
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 84392.7266
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 71793.7422
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 59884.0820
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 48884.7539
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 38982.1172
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 30263.5371
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 22856.6289
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 16734.9746
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 11862.9375
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8117.4150
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 5369.9897
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3431.1277
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2133.5908
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1311.3502
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 794.7637
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 506.5747
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 347.1776
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 257.9328
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 222.0934
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 200.6835
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 191.5807
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 188.1616
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 186.6627
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 186.4455
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 185.9075
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 185.9493
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 185.7791
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 185.6967
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 185.6118
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 185.5972
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
train_rmse: 13.618380407225274
test rmse : 16.169771761955662

In [108]:
test_mse = mean_squared_error(y_test, ypred_test)
test_rmse = np.sqrt(test_mse)
print("test rmse :", test_rmse)

test rmse : 15.930239613546826

first started with 3 hidden layers or neurons

In [121]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
from sklearn.metrics import mean_squared_error

# Design of Neural Network
nn3 = Sequential()

# Input layer
nn3.add(Input(shape=(4,)))

#  applyting 3 Hidden layers

nn3.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))

nn3.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))

nn3.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))

# Output layer
nn3.add(Dense(units=1,
              activation='linear',
              kernel_initializer='he_uniform'))

# Compile
nn3.compile(optimizer='adam',
            loss='mean_squared_error')

# Train
nn3.fit(x_train,
        y_train,
        batch_size=32,
        epochs=50)

# Predictions
ypred_train = nn3.predict(x_train)
ypred_test = nn3.predict(x_test)

# Train Evaluation
train_mse = mean_squared_error(y_train, ypred_train)
train_rmse = np.sqrt(train_mse)
print("Train RMSE:", train_rmse)

# Test Evaluation
test_mse = mean_squared_error(y_test, ypred_test)
test_rmse = np.sqrt(test_mse)
print("Test RMSE:", test_rmse)

Epoch 1/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 237173.5469
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237100.9531
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 236957.9844
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 236705.8906
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 236282.3281
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 235524.4062
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 234108.8594
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 231711.5156
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 228035.6719
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 222714.2344
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 215347.9062
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 205542.0625
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 192987.7500
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 177458.3438
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 158933.4531
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 137644.2344
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 114226.0391
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 89697.6562
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 65469.0781
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 43381.5391
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 25107.4414
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 12062.1084
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4387.3525
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1088.6901
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 244.8648
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 230.7172
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 286.8828
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 259.4721
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 211.5803
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 191.0669
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 183.5366
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 185.9267
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 186.0818
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 184.9836
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 184.6954
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 184.2735
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 184.1094
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 184.0019
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 183.8898
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 183.6573
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 183.5159
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 183.3891
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 183.2661
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 183.0851
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 183.0317
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 182.9270
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 182.8668
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 182.5997
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 182.3414
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 182.2292
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
Train RMSE: 13.494865526492266
Test RMSE: 16.025344479876747

*Now we will try neuron model with 1 hidden layers means nn2--> 1 hidden nuerons

In [124]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
from sklearn.metrics import mean_squared_error

# Design of Neural Network
nn1 = Sequential()

# Input layer
nn1.add(Input(shape=(4,)))

# Hidden layers
nn1.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))

# Output layer
nn1.add(Dense(units=1,
              activation='linear',
              kernel_initializer='he_uniform'))

# Compile
nn1.compile(optimizer='adam',
            loss='mean_squared_error')

# Train
nn1.fit(x_train,
        y_train,
        batch_size=32,
        epochs=50)

# Predictions
ypred_train = nn1.predict(x_train)
ypred_test = nn1.predict(x_test)

# Train Evaluation
train_mse = mean_squared_error(y_train, ypred_train)
train_rmse = np.sqrt(train_mse)
print("Train RMSE:", train_rmse)

# Test Evaluation
test_mse = mean_squared_error(y_test, ypred_test)
test_rmse = np.sqrt(test_mse)
print("Test RMSE:", test_rmse)

Epoch 1/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 234311.6406
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 221320.8281
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 208622.8281
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 199154.1562
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 190353.9688
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 181196.4688
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 171720.7500
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 161948.4375
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 151957.4844
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 141794.3125
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 131538.2344
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 121272.1172
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 111071.7031
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 101019.9219
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 91204.3672
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 81694.2109
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 72582.7812
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 63933.7539
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 55796.4414
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 48233.0781
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 41273.6758
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 34951.3086
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 29269.5586
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 24246.0117
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 19831.9277
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 16056.7842
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12812.1650
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 10116.6846
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7884.8159
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6072.2075
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4635.4312
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3489.7659
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2613.2388
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1946.8595
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1446.5708
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1071.8131
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 806.7909
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 615.7185
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 482.2581
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 389.6127
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 326.5033
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 281.6400
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 253.8074
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 235.1683
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 222.6997
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 215.2034
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 210.1826
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 207.6305
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 205.3495
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 204.1076
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Train RMSE: 14.279350229224685
Test RMSE: 16.832734079545325

Now will try 2 hidden layers means nn2

In [126]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
from sklearn.metrics import mean_squared_error

# Design of Neural Network
nn2 = Sequential()

# Input layer
nn2.add(Input(shape=(4,)))

# Hidden layers
nn2.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))

nn2.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))

# Output layer
nn2.add(Dense(units=1,
              activation='linear',
              kernel_initializer='he_uniform'))

# Compile
nn2.compile(optimizer='adam',
            loss='mean_squared_error')

# Train
nn2.fit(x_train,
        y_train,
        batch_size=32,
        epochs=100)

# Predictions
ypred_train = nn2.predict(x_train)
ypred_test = nn2.predict(x_test)

# Train Evaluation
train_mse = mean_squared_error(y_train, ypred_train)
train_rmse = np.sqrt(train_mse)
print("Train RMSE:", train_rmse)

# Test Evaluation
test_mse = mean_squared_error(y_test, ypred_test)
test_rmse = np.sqrt(test_mse)
print("Test RMSE:", test_rmse)

Epoch 1/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 236451.0312
Epoch 2/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 234068.3438
Epoch 3/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 231542.0625
Epoch 4/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 228220.3594
Epoch 5/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 223662.0938
Epoch 6/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 217662.6406
Epoch 7/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 210065.0938
Epoch 8/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 200749.5156
Epoch 9/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 189684.5938
Epoch 10/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 176885.6875
Epoch 11/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 162488.1406
Epoch 12/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 146695.4844
Epoch 13/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 129824.1250
Epoch 14/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 112279.6562
Epoch 15/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 94552.1797
Epoch 16/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 77196.1406
Epoch 17/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 60797.7070
Epoch 18/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 45905.5430
Epoch 19/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 32976.8711
Epoch 20/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 22387.7051
Epoch 21/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 14191.0273
Epoch 22/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8334.5596
Epoch 23/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4495.3223
Epoch 24/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2208.6174
Epoch 25/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1010.3801
Epoch 26/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 467.6814
Epoch 27/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 253.1206
Epoch 28/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 190.8064
Epoch 29/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 177.4431
Epoch 30/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 180.1135
Epoch 31/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 180.6165
Epoch 32/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 180.4182
Epoch 33/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 179.5035
Epoch 34/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 179.0938
Epoch 35/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 178.4559
Epoch 36/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 178.1743
Epoch 37/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 178.1495
Epoch 38/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 178.0374
Epoch 39/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 177.8976
Epoch 40/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 177.7591
Epoch 41/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 177.7103
Epoch 42/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 177.5276
Epoch 43/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 177.4765
Epoch 44/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 177.3594
Epoch 45/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 177.1052
Epoch 46/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 177.0359
Epoch 47/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 176.9665
Epoch 48/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 176.7968
Epoch 49/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 176.6429
Epoch 50/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 176.5293
Epoch 51/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 176.4400
Epoch 52/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 176.4343
Epoch 53/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 176.1432
Epoch 54/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 176.2078
Epoch 55/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 176.1401
Epoch 56/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 175.7730
Epoch 57/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 175.5808
Epoch 58/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 175.7016
Epoch 59/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 175.4192
Epoch 60/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 175.1541
Epoch 61/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 175.0080
Epoch 62/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 174.9224
Epoch 63/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 174.7364
Epoch 64/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 174.6236
Epoch 65/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 174.5426
Epoch 66/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 174.4217
Epoch 67/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 174.1307
Epoch 68/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 174.0577
Epoch 69/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 173.9159
Epoch 70/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 173.7541
Epoch 71/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 173.5683
Epoch 72/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 173.4390
Epoch 73/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 173.2460
Epoch 74/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 173.0025
Epoch 75/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 173.0712
Epoch 76/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 172.7649
Epoch 77/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 172.6980
Epoch 78/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 172.6595
Epoch 79/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 172.3759
Epoch 80/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 172.1172
Epoch 81/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 171.9135
Epoch 82/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 171.7108
Epoch 83/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 171.5223
Epoch 84/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 171.4009
Epoch 85/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 171.2785
Epoch 86/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 171.3096
Epoch 87/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 171.2896
Epoch 88/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 170.7153
Epoch 89/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 170.5031
Epoch 90/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 170.1819
Epoch 91/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 170.0338
Epoch 92/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 170.3171
Epoch 93/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 169.7037
Epoch 94/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 169.4419
Epoch 95/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 169.3799
Epoch 96/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 169.1911
Epoch 97/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 168.9955
Epoch 98/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 168.8159
Epoch 99/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 168.6342
Epoch 100/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 168.4028
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
Train RMSE: 12.971180862646852
Test RMSE: 15.391708504897846

So from the following analysis we get that hidden neuron with 3 layers giving the best prediction nn3 --> loss-->183, train-rmse-->13, test_rmse-->16

In [129]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
from sklearn.metrics import mean_squared_error

# Design of Neural Network
nn4 = Sequential()

# Input layer
nn4.add(Input(shape=(4,)))

# Hidden layers
nn4.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))

nn4.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))
nn4.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))

nn4.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))

# Output layer
nn4.add(Dense(units=1,
              activation='linear',
              kernel_initializer='he_uniform'))

# Compile
nn4.compile(optimizer='adam',
            loss='mean_squared_error')

# Train
nn4.fit(x_train,
        y_train,
        batch_size=32,
        epochs=100)

# Predictions
ypred_train = nn4.predict(x_train)
ypred_test = nn4.predict(x_test)

# Train Evaluation
train_mse = mean_squared_error(y_train, ypred_train)
train_rmse = np.sqrt(train_mse)
print("Train RMSE:", train_rmse)

# Test Evaluation
test_mse = mean_squared_error(y_test, ypred_test)
test_rmse = np.sqrt(test_mse)
print("Test RMSE:", test_rmse)

Epoch 1/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 237185.3438
Epoch 2/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237153.6562
Epoch 3/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237099.0625
Epoch 4/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 236994.2188
Epoch 5/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 236784.9531
Epoch 6/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 236377.9062
Epoch 7/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 235612.9375
Epoch 8/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 234212.5938
Epoch 9/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 231760.1094
Epoch 10/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 227656.0156
Epoch 11/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 221119.1406
Epoch 12/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 211161.4219
Epoch 13/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 196704.8281
Epoch 14/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 176700.4219
Epoch 15/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 150480.1406
Epoch 16/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 118368.9844
Epoch 17/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 81891.7188
Epoch 18/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 42788.8594
Epoch 19/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 12681.5557
Epoch 20/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 991.7374
Epoch 21/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1540.3732
Epoch 22/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1580.1365
Epoch 23/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 426.5462
Epoch 24/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 220.6732
Epoch 25/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 286.9229
Epoch 26/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 236.8905
Epoch 27/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 193.8137
Epoch 28/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 196.8380
Epoch 29/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 199.0705
Epoch 30/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 196.2585
Epoch 31/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 193.8637
Epoch 32/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 194.4300
Epoch 33/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 193.7628
Epoch 34/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 193.7449
Epoch 35/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 193.3982
Epoch 36/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 192.9902
Epoch 37/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 192.7855
Epoch 38/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 192.5872
Epoch 39/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 192.4874
Epoch 40/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 192.3923
Epoch 41/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 192.0795
Epoch 42/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 191.7838
Epoch 43/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 191.5964
Epoch 44/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 191.3410
Epoch 45/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 191.0138
Epoch 46/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 190.7227
Epoch 47/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 190.4390
Epoch 48/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 190.3549
Epoch 49/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 189.9553
Epoch 50/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 190.0121
Epoch 51/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 189.9035
Epoch 52/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 189.2533
Epoch 53/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 189.2544
Epoch 54/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 188.9381
Epoch 55/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 188.6182
Epoch 56/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 188.4160
Epoch 57/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 188.4467
Epoch 58/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 187.5847
Epoch 59/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 188.2726
Epoch 60/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 187.3227
Epoch 61/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 186.6726
Epoch 62/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 187.0252
Epoch 63/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 187.0729
Epoch 64/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 186.1160
Epoch 65/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 186.1127
Epoch 66/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 185.5990
Epoch 67/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 185.3532
Epoch 68/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 185.4444
Epoch 69/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 186.2529
Epoch 70/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 184.7446
Epoch 71/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 184.1748
Epoch 72/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 184.1044
Epoch 73/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 184.0260
Epoch 74/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 184.1031
Epoch 75/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 183.8338
Epoch 76/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 182.8538
Epoch 77/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 182.2416
Epoch 78/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 182.4366
Epoch 79/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 182.1020
Epoch 80/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 181.2430
Epoch 81/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 181.0389
Epoch 82/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 180.4870
Epoch 83/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 180.3734
Epoch 84/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 180.5142
Epoch 85/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 179.6114
Epoch 86/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 180.5899
Epoch 87/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 179.3882
Epoch 88/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 178.6955
Epoch 89/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 178.7622
Epoch 90/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 178.1123
Epoch 91/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 177.9289
Epoch 92/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 178.0132
Epoch 93/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 176.8732
Epoch 94/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 177.1119
Epoch 95/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 176.5120
Epoch 96/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 177.8138
Epoch 97/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 176.0088
Epoch 98/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 175.9188
Epoch 99/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 175.0308
Epoch 100/100
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 174.7295
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
Train RMSE: 13.203008535546845
Test RMSE: 15.642328912407693

Adding 5th neuron to the layer

In [133]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense
from sklearn.metrics import mean_squared_error

# Design of Neural Network
nn5 = Sequential()

# Input layer
nn5.add(Input(shape=(4,)))

# Hidden layers
nn5.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))

nn5.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))
nn5.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))

nn5.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))

nn5.add(Dense(units=8,
              activation='relu',
              kernel_initializer='uniform'))

# Output layer
nn5.add(Dense(units=1,
              activation='linear',
              kernel_initializer='he_uniform'))


# Compile
nn5.compile(optimizer='adam',
            loss='mean_squared_error')


# Train
nn5.fit(x_train,
        y_train,
        batch_size=32,
        epochs=50)

# Predictions
ypred_train = nn5.predict(x_train)
ypred_test = nn5.predict(x_test)

# Train Evaluation
train_mse = mean_squared_error(y_train, ypred_train)
train_rmse = np.sqrt(train_mse)
print("Train RMSE:", train_rmse)

# Test Evaluation
test_mse = mean_squared_error(y_test, ypred_test)
test_rmse = np.sqrt(test_mse)
print("Test RMSE:", test_rmse)

Epoch 1/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 237180.3281
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237140.3594
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 237077.9844
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 236959.4688
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 236703.4062
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 236126.2344
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 234861.2500
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 232225.7344
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 227054.4844
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 217443.6562
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 200636.3125
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 173251.9375
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 132682.4688
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 80431.1250
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 28646.9453
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2139.3726
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 3972.1709
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2392.4917
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 246.4546
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 578.0558
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 352.0662
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 184.0396
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 215.2857
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 188.9993
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 181.5668
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 180.6905
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 176.1601
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 177.6777
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 176.2159
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 175.5893
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 175.5248
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 175.4591
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 175.2632
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 174.9452
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 174.7480
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 174.0438
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 174.1502
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 174.3306
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 173.4229
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 173.4131
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 172.8387
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 173.0729
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 172.3289
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 172.3096
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 171.7560
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 171.7470
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 171.1568
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 170.7044
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 170.9503
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 170.3238
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
Train RMSE: 13.038635290646003
Test RMSE: 15.517250399631537

from above analysis we can coclude that test and train rmse are close to each other so this model is performed well on ANN

# Train RMSE > Test RMSE (underfitting model)
# Train RMSE < Test RMSE (overfitting problem)