In [1]:
import pandas as pd

In [11]:
df = pd.read_csv(r"C:\EXCEL DATA\NLP.txt",  sep="\t", names=["Text", "Labels"])

In [12]:
df

                                                 Text  Labels
0   | Text                                        ...     NaN
1   | --------------------------------------------...     NaN
2   | Hi, where are you?                          ...     NaN
3   | Call me when you reach home.                ...     NaN
4   | Have you completed the assignment?          ...     NaN
5   | Let's meet after lunch.                     ...     NaN
6   | Can you send me the report?                 ...     NaN
7   | Happy anniversary!                          ...     NaN
8   | I'll be late today.                         ...     NaN
9   | Please check your email.                    ...     NaN
10  | Thanks for your help.                       ...     NaN
11  | Are you free tomorrow?                      ...     NaN
12  | Congratulations! Claim your free gift now!  ...     NaN
13  | Win ₹5 lakh instantly. Click here.          ...     NaN
14  | Limited-time offer! Shop today.             ...     NaN
15  | Your account has been locked. Verify now.   ...     NaN
16  | Get rich quickly from home.                 ...     NaN
17  | Free vacation package waiting for you!      ...     NaN
18  | Lowest EMI loan approved instantly.         ...     NaN
19  | Claim your cashback reward today.           ...     NaN
20  | Update your KYC immediately to avoid suspens...     NaN
21  | Exclusive deal! 90% OFF only today.         ...     NaN

In [8]:
df['message']

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
7    NaN
8    NaN
9    NaN
10   NaN
11   NaN
12   NaN
13   NaN
14   NaN
15   NaN
16   NaN
17   NaN
18   NaN
19   NaN
20   NaN
21   NaN
Name: message, dtype: float64

In [16]:
df['Labels']=df['Labels'].fillna('person')

In [17]:
df

                                                 Text  Labels
0   | Text                                        ...  person
1   | --------------------------------------------...  person
2   | Hi, where are you?                          ...  person
3   | Call me when you reach home.                ...  person
4   | Have you completed the assignment?          ...  person
5   | Let's meet after lunch.                     ...  person
6   | Can you send me the report?                 ...  person
7   | Happy anniversary!                          ...  person
8   | I'll be late today.                         ...  person
9   | Please check your email.                    ...  person
10  | Thanks for your help.                       ...  person
11  | Are you free tomorrow?                      ...  person
12  | Congratulations! Claim your free gift now!  ...  person
13  | Win ₹5 lakh instantly. Click here.          ...  person
14  | Limited-time offer! Shop today.             ...  person
15  | Your account has been locked. Verify now.   ...  person
16  | Get rich quickly from home.                 ...  person
17  | Free vacation package waiting for you!      ...  person
18  | Lowest EMI loan approved instantly.         ...  person
19  | Claim your cashback reward today.           ...  person
20  | Update your KYC immediately to avoid suspens...  person
21  | Exclusive deal! 90% OFF only today.         ...  person

In [19]:
df['Text'].unique()

array(['| Text                                             | Label |',
       '| ------------------------------------------------ | ----- |',
       '| Hi, where are you?                               | Ham   |',
       '| Call me when you reach home.                     | Ham   |',
       '| Have you completed the assignment?               | Ham   |',
       "| Let's meet after lunch.                          | Ham   |",
       '| Can you send me the report?                      | Ham   |',
       '| Happy anniversary!                               | Ham   ',
       "| I'll be late today.                              | Ham   |",
       '| Please check your email.                         | Ham   |',
       '| Thanks for your help.                            | Ham   |',
       '| Are you free tomorrow?                           | Ham   |',
       '| Congratulations! Claim your free gift now!       | Spam  |',
       '| Win ₹5 lakh instantly. Click here.               | Spam  |',
       '| Limited-time offer! Shop today.                  | Spam  |',
       '| Your account has been locked. Verify now.        | Spam  |',
       '| Get rich quickly from home.                      | Spam  |',
       '| Free vacation package waiting for you!           | Spam  |',
       '| Lowest EMI loan approved instantly.              | Spam  |',
       '| Claim your cashback reward today.                | Spam  |',
       '| Update your KYC immediately to avoid suspension. | Spam  |',
       '| Exclusive deal! 90% OFF only today.              | Spam  |'],
      dtype=object)

In [20]:
df['Text'].nunique()

22

In [23]:
df

                                                 Text  Labels
0   | Text                                        ...  person
1   | --------------------------------------------...  person
2   | Hi, where are you?                          ...  person
3   | Call me when you reach home.                ...  person
4   | Have you completed the assignment?          ...  person
5   | Let's meet after lunch.                     ...  person
6   | Can you send me the report?                 ...  person
7   | Happy anniversary!                          ...  person
8   | I'll be late today.                         ...  person
9   | Please check your email.                    ...  person
10  | Thanks for your help.                       ...  person
11  | Are you free tomorrow?                      ...  person
12  | Congratulations! Claim your free gift now!  ...  person
13  | Win ₹5 lakh instantly. Click here.          ...  person
14  | Limited-time offer! Shop today.             ...  person
15  | Your account has been locked. Verify now.   ...  person
16  | Get rich quickly from home.                 ...  person
17  | Free vacation package waiting for you!      ...  person
18  | Lowest EMI loan approved instantly.         ...  person
19  | Claim your cashback reward today.           ...  person
20  | Update your KYC immediately to avoid suspens...  person
21  | Exclusive deal! 90% OFF only today.         ...  person

In [24]:
df['Text'].value_counts()

Text
| Text                                             | Label |    1
| ------------------------------------------------ | ----- |    1
| Hi, where are you?                               | Ham   |    1
| Call me when you reach home.                     | Ham   |    1
| Have you completed the assignment?               | Ham   |    1
| Let's meet after lunch.                          | Ham   |    1
| Can you send me the report?                      | Ham   |    1
| Happy anniversary!                               | Ham        1
| I'll be late today.                              | Ham   |    1
| Please check your email.                         | Ham   |    1
| Thanks for your help.                            | Ham   |    1
| Are you free tomorrow?                           | Ham   |    1
| Congratulations! Claim your free gift now!       | Spam  |    1
| Win ₹5 lakh instantly. Click here.               | Spam  |    1
| Limited-time offer! Shop today.                  | Spam  |    1
| Your account has been locked. Verify now.        | Spam  |    1
| Get rich quickly from home.                      | Spam  |    1
| Free vacation package waiting for you!           | Spam  |    1
| Lowest EMI loan approved instantly.              | Spam  |    1
| Claim your cashback reward today.                | Spam  |    1
| Update your KYC immediately to avoid suspension. | Spam  |    1
| Exclusive deal! 90% OFF only today.              | Spam  |    1
Name: count, dtype: int64

In [25]:
df.shape

(22, 2)

Data Understanding

In [26]:
df["Labels"].unique()

array(['person'], dtype=object)

In [27]:
df["Labels"].value_counts()

Labels
person    22
Name: count, dtype: int64

In [28]:
df.columns.tolist()

['Text', 'Labels']

Data Exploration

In [29]:
df["Labels"].unique().tolist()

['person']

In [30]:
df["Text"].unique()

array(['| Text                                             | Label |',
       '| ------------------------------------------------ | ----- |',
       '| Hi, where are you?                               | Ham   |',
       '| Call me when you reach home.                     | Ham   |',
       '| Have you completed the assignment?               | Ham   |',
       "| Let's meet after lunch.                          | Ham   |",
       '| Can you send me the report?                      | Ham   |',
       '| Happy anniversary!                               | Ham   ',
       "| I'll be late today.                              | Ham   |",
       '| Please check your email.                         | Ham   |',
       '| Thanks for your help.                            | Ham   |',
       '| Are you free tomorrow?                           | Ham   |',
       '| Congratulations! Claim your free gift now!       | Spam  |',
       '| Win ₹5 lakh instantly. Click here.               | Spam  |',
       '| Limited-time offer! Shop today.                  | Spam  |',
       '| Your account has been locked. Verify now.        | Spam  |',
       '| Get rich quickly from home.                      | Spam  |',
       '| Free vacation package waiting for you!           | Spam  |',
       '| Lowest EMI loan approved instantly.              | Spam  |',
       '| Claim your cashback reward today.                | Spam  |',
       '| Update your KYC immediately to avoid suspension. | Spam  |',
       '| Exclusive deal! 90% OFF only today.              | Spam  |'],
      dtype=object)

In [31]:
#to check no of unique valuesi in each columns

df['Text'].nunique()

22

In [34]:
df['Labels'].nunique()

1

In [35]:
#to check no of missing calues
df.isnull().sum()

Text      0
Labels    0
dtype: int64

In [36]:
# to remove missing valyes
df= df.dropna()

Transform
Text Cleaning
Remove Punctuation
Remove stopwords
Stemming

In [37]:
import nltk
import re
from nltk.corpus import stopwords  #set of text/values
from nltk.stem import PorterStemmer
ps = PorterStemmer()

corpus = []
for i in range(len(df)):
    rp = re.sub('[^a-zA-Z]', " ", df['Text'][i])
    rp = rp.lower()
    rp = rp.split()
    rp = [ps.stem(word) for word in rp if not word in stopwords.words('english')]
    rp = " ".join(rp)
    corpus.append(rp)

In [38]:
corpus

['text label',
 '',
 'hi ham',
 'call reach home ham',
 'complet assign ham',
 'let meet lunch ham',
 'send report ham',
 'happi anniversari ham',
 'late today ham',
 'pleas check email ham',
 'thank help ham',
 'free tomorrow ham',
 'congratul claim free gift spam',
 'win lakh instantli click spam',
 'limit time offer shop today spam',
 'account lock verifi spam',
 'get rich quickli home spam',
 'free vacat packag wait spam',
 'lowest emi loan approv instantli spam',
 'claim cashback reward today spam',
 'updat kyc immedi avoid suspens spam',
 'exclus deal today spam']

Vectorization
for input variable : count_vectorization
for output variable : label-encoding

In [ ]:
corpora                    corpus

sentence                    : mutliple words
parapgraph                   : multiple semtence
lesson/chapter             : multiple paragraph

In [39]:
#count vectorization

from sklearn.feature_extraction.text import CountVectorizer  #BOW- Bag of words
cv = CountVectorizer(max_features=None)
x = cv.fit_transform(corpus).toarray()
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(22, 59))

In [40]:
x.shape

(22, 59)

In [42]:
#Label encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Labels'] = le.fit_transform(df[['Labels']])
df['Labels']

C:\Users\saipr\anaconda3\envs\tensorflow_env\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
Name: Labels, dtype: int64

In [43]:
y = df['Labels']

In [44]:
y

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
Name: Labels, dtype: int64

In [45]:
y.shape

(22,)

In [46]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=42)

train the machine wirth ML algorithm using train data
Multicategory Naive-Bayes

In [49]:
from sklearn.naive_bayes import MultinomialNB    #import ML algorithm
model = MultinomialNB()  #save as model name
model.fit(x_train, y_train)

MultinomialNB()

#evaluate your model
train accuracy
test accuracy
cross validation

In [51]:
ypred_train = model.predict(x_train)
from sklearn.metrics import accuracy_score
accuracy_score(y_train, ypred_train)

1.0

In [52]:
ypred_test = model.predict(x_test)
accuracy_score(y_test, ypred_test)

1.0

In [54]:
from sklearn.model_selection import cross_val_score
cross_val_score(model, x,y,cv=5).mean()

np.float64(1.0)

Model selection :
- condition1 --> test accuracy =Train accuracy
- condtion2 --> test accuracy = cross val score

--> model said to be good model if it satisfy above 2 conditions
--> Train accuracy > Test accuracy Overfitting
Solution --> 1.reduce no of columns==input/features

--> Train accuracy < Test Accuracy Underfitting
solution --> add more data

Predict on New data

In [56]:
input_mail = "You have won a lottery of 1cr"

#Preprocessing the data

corpus = []
rp = re.sub("[^a-zA-Z]", " ", input_mail)
rp = rp.lower()
rp = rp.split()
rp = [ps.stem(word) for word in rp if not word in set (stopwords.words('english'))]

rp = " ".join(rp)
corpus.append(rp)

#text vectorization

x = cv.transform(corpus).toarray()

In [59]:
#Prediction

pred = model.predict(x)
if pred == 1:
    print("Haam")
else:
    print("spam")

spam